### ISSUE TITLE
FIX is not getting run on commit

### ISSUE THREAD

**Issue by shani-terminus** [GetTerminus/eslint-config-frontend#27]
In VSCode, we were not able to configure linters to run on save, so if for any reason the linter is not run manually, the build will fail due to fixable issues.

![Screen Shot 2019-07-12 at 7.50.18 AM.png](https://images.zenhubusercontent.com/5bdc9e4ea977220c77bd0f30/cb304758-537d-417a-8341-5a41d47e67dd)

**Comment by benjamincharity** [comment]
This configuration has no control how VSCode runs it's linters so it's not really an issue with this package. Sounds like VSCode users will need to manually run the linter. You may want to open a ticket in the VSCode repository (or the appropriate VSCode linter repo).

Aside from VSCode specifically, this should still be caught by the UI library's precommit hook that runs the linters. You _should_ get blocked before committing if linting doesn't pass. 

I have confirmed that husky is no longer running the git hook for me either (though I have confirmed the hook is set up). I will open a ticket in the UI library to fix Husky it there.
